server:
  port: 12002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.103:3306/my_blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      max-active: 20
      initial-size: 5
      max-wait: 5000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  type-aliases-package: com.xuxin.model
  mapper-locations: classpath:mapper/*Mapper.xml